name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: ./.github/actions/build-user-config
        name: Build
